class RelationTypeEnum:
    
    DEFINES = "DEFINES"
    ISDEFINED = "ISDEFINED"
    CONTAINS = "CONTAINS"
    ISCONTAINED = "ISCONTAINED"
    HASFIELD = "HASFIELD"
    ISFIELDOF = "ISFIELDOF"
    CALLS = "CALLS"
    ISCALLED = "ISCALLED"
